name: imgx
description: "Flutter package for loading images from URLs (PNG, JPG, WEBP, GIF) with memory/disk caching, expiration, retry mechanism, and progress tracking for smooth server handling."
version: 0.1.4
homepage: "https://github.com/huygenlabs/imgx"

environment:
  sdk: ^3.5.4
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  shared_preferences: ^2.3.5
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.5

topics:
  - image
  - image-loading
  - image-caching
  - image-download
  - image-retry
